language: bash
sudo: required

services:
  - docker

script:
  - shellcheck *.sh
  - ./build_docker.sh

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "artifacts/pngquant.gz"
  skip_cleanup: true
  on:
    tags: true
